### ISSUE TITLE
Update Documentation breaking change 1.5

### ISSUE THREAD

**Issue by tomdillien91** [digipolisantwerp/smart-table_widget_angular#19]
Since upgrading to the newest release of version 1.5,
I've experienced a console error on every instance of the smart table widget.
It turns out that you need to add an extra line of config in the module.

 SmartTableModule.forRoot({
      identifier: 'aui-smarttable-ngx',
      storageType: 'sessionStorage' || 'localStorage' || 'memory'
    }),

Before, The storageType was not needed.
Can anyone put this in the documentation?

**Comment by MichaelCastiau** [comment]
@tomdillien91  Thanks for reporting this issue. Steps will be taken to fix the breaking change, since it was not meant for one to exist.

**Comment by MichaelCastiau** [comment]
https://github.com/digipolisantwerp/smart-table_widget_angular/pull/20

**Comment by TriangleJuice** [comment]
Fixed by #20
