### ISSUE TITLE
defaultSortOrder isn't passed on first call to entity endpoint

### ISSUE THREAD

**Issue by Jonah-Jordan** [digipolisantwerp/smart-table_widget_angular#31]
The default sort order option isn't sent on the initial request.

![image](https://user-images.githubusercontent.com/22741097/89422445-a3d36480-d735-11ea-9057-9cdf26d3ca1a.png)

![image](https://user-images.githubusercontent.com/22741097/89422482-b2ba1700-d735-11ea-92c1-047b99bec20b.png)

**Comment by jsebrech** [comment]
Thank you for reporting. This behavior is by design. The purpose of defaultSortOrder is for the server to communicate to the client what the default sort order will be if the client does not provide sorting parameters in the query.
