### ISSUE TITLE
Bug: Column order is persisted to localStorage

### ISSUE THREAD

**Issue by stefanpante** [digipolisantwerp/smart-table_widget_angular#35]
When saving which columns to show, the order is also persisted to localStorage.
When the BE developer changes the order in the config call, 
the order in localStorage is respected, not the order defined by the config call.
(I was not sure if this was a bug, but @jsebrech said it was, because ordering the columns is not a feature in the component).

temporary workaround is to clear localStorage when developer changes the order of the columns.

**Comment by jsebrech** [comment]
Column reordering was added as a feature, so now this is actually by design. When changing column order server-side you can force updated settings by changing the `storageIdentifier` in the server-side configuration.
