### ISSUE TITLE
Column selecting is not  intuitive

### ISSUE THREAD

**Issue by RobbePeeters** [digipolisantwerp/smart-table_widget_angular#47]
When clicking a checkbox, but not selecting 'Toepassen', the column is not added. When opening up the pop up again, the checkbox is still selected.

More details in this video: 
https://user-images.githubusercontent.com/34277316/103626848-0d51dc00-4f3d-11eb-8fed-c7ac4d00ff88.mp4

**Comment by MichaelCastiau** [comment]
https://github.com/digipolisantwerp/smart-table_widget_angular/pull/48
